

class Cluster:
    '''
    using the df generated by the Scraping tool, we are going to plot the Senators, and cluster them together
    '''
    def __init__(self, df):
        self.df = df


    def cluster(self):
        '''
        This function will return a dataframe with the senators clustered together
        '''
        # encode the senators
        print("nothing yet")